### ISSUE TITLE
Problem With MacOS macOS Sequoia and iMAC with M3

### ISSUE THREAD

**Issue by bentoart** [erpnet/ErpNet.FP#190]
When we try to start the ErpNet.FP console aftrer few seconds system give us error:

./ErpNet.FP.Server
Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.IO.Ports.SafeSerialDeviceHandle'.
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at Interop.Termios.TermiosDrain(SafeSerialDeviceHandle handle)
   at System.IO.Ports.SerialStream.Flush()
   at System.IO.Ports.SerialPort.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at ErpNet.FP.Core.Transports.ComTransport.Channel.Close() in C:\Code\ErpNet.FP\ErpNet.FP.Core\Transports\ComTransport.cs:line 173
   at ErpNet.FP.Core.Transports.ComTransport.Channel.IdleTimerElapsed(Object state) in C:\Code\ErpNet.FP\ErpNet.FP.Core\Transports\ComTransport.cs:line 122
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
 

**Describe the device(s) you are using**
iMAC M3
Eltrade B1-KL

**How To Reproduce**
1. Install dot net 9
2. Extract all files ErpNet.FP.Server
3. sudo spctl --master-disable

**Expected behavior**
To start ErpNet.FP.Server

**Comment by moynzzz** [comment]
Any info about this error I have the same?
